-- MySQL Script generated by MySQL Workbench
-- Sun Nov 28 22:32:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gdfS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gdfS` ;

-- -----------------------------------------------------
-- Schema gdfS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gdfS` DEFAULT CHARACTER SET utf8 ;
USE `gdfS` ;

-- -----------------------------------------------------
-- Table `gdfS`.`COUNTRY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gdfS`.`COUNTRY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODE` CHAR(2) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gdfS`.`USER_ADDRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gdfS`.`USER_ADDRESS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ADDRESS_LINE` VARCHAR(45) NOT NULL,
  `POST_CODE` VARCHAR(15) NOT NULL,
  `STATE` VARCHAR(45) NOT NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `COUNTRY_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_USER_ADDRESS_COUNTRY_idx` (`COUNTRY_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USER_ADDRESS_COUNTRY`
    FOREIGN KEY (`COUNTRY_ID`)
    REFERENCES `gdfS`.`COUNTRY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gdfS`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gdfS`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(75) NOT NULL,
  `DOB` DATE NULL,
  `USER_ADDRESS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `USER_ADDRESS_ID`),
  INDEX `fk_USER_USER_ADDRESS1_idx` (`USER_ADDRESS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USER_USER_ADDRESS1`
    FOREIGN KEY (`USER_ADDRESS_ID`)
    REFERENCES `gdfS`.`USER_ADDRESS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
